language: node_js
node_js:
- 12.8.0
install: yarn
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'thewebdev-deploy'
  skip_cleanup: true
  acl: public_read
  local_dir: public